# Generated by Django 3.1.2 on 2020-11-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curiosidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Introduzca un breve título de la curiosidad', max_length=200)),
                ('description', models.TextField(help_text='Introduzca una breve descripción de la curiosidad', max_length=1000)),
            ],
        ),
    ]
