# Generated by Django 3.1.2 on 2020-11-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoomi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('comentario', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='curiosidad',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='curiosidad',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='curiosidad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curiosidad',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
