# Generated by Django 3.1.2 on 2020-11-07 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagoomi', '0002_auto_20201106_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curiosidad',
            options={},
        ),
        migrations.RenameField(
            model_name='curiosidad',
            old_name='id',
            new_name='iden',
        ),
    ]
